name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          token: ${{ secrets.SECRET_NAME}}
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_NAME }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=EgorLq_Credit-Conveyor